name: Build Rijksmuseum app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest
    - name: Build debug APK
      run: ./gradlew assembleDebug
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
       name: test-results
       retention-days: 3
       path: |
         app/build/reports/tests/
         app/build/test-results/
